using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class ObstacleSpawner : MonoBehaviour
{
    public GameObject obstacle1, obstacle2, obstacle3, obstacle4;
    [HideInInspector]
    public float obstacleInterfal = 2.6f;
    // Start is called before the first frame update
    void Start()
    {
        StartCoroutine("spawnObstacle");
    }

    // Update is called once per frame
    void Update()
    {
        if (GameObject.FindGameObjectWithTag("Player").GetComponent<PlayerMov>().isGameOver)
        {
            StopCoroutine("spawnObstacle");
        }
    }
    private void spawnObstacles()
    {
        int random = Random.Range(1,5);
        if(random == 1)
        {
            Instantiate(obstacle1, new Vector3(transform.position.x - 6, -1.5f, 0), Quaternion.identity);
        }
        if(random == 2)
        {
            Instantiate(obstacle2, new Vector3(transform.position.x - 7, -1.5f, 0), Quaternion.identity);
        }
        if(random == 3)
        {
            Instantiate(obstacle3, new Vector3(transform.position.x - 5, -1.5f, 0), Quaternion.identity);
        }
        if(random == 4)
        {
            Instantiate(obstacle4, new Vector3(transform.position.x - 4, -1.5f, 0), Quaternion.identity);
        }
    }
    IEnumerator spawnObstacle() 
    {
        while (true)
        {
            spawnObstacles();
            yield return new WaitForSeconds(obstacleInterfal);
        }
    }
}
